### ISSUE TITLE
npm error when running '$ npm install && npm run openshift'

### ISSUE THREAD

**Issue by austincunningham** [bucharest-gold/nodejs-rest-http-crud#40]
## What?
Script looks to be falling over on **npm run openshift** when run locally with openshift origin (oc cluster up).
Reproduced on fedora and mint and node 6 and 8

## Workaround 
install nodeshift globally 
**npm install nodeshift -g**
and rerun the script **nodeshift --osc.strictSSL=false** 

## npm-debug.log
```
11 silly lifecycle booster-crud-nodejs@1.0.0~openshift: Args: [ '-c', 'nodeshift --osc.strictSSL=false' ]
12 silly lifecycle booster-crud-nodejs@1.0.0~openshift: Returned: code: 1  signal: null
13 info lifecycle booster-crud-nodejs@1.0.0~openshift: Failed to exec openshift script
14 verbose stack Error: booster-crud-nodejs@1.0.0 openshift: `nodeshift --osc.strictSSL=false`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/austincunningham/.nvm/versions/node/v6.11.4/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/austincunningham/.nvm/versions/node/v6.11.4/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid booster-crud-nodejs@1.0.0
16 verbose cwd /home/austincunningham/Downloads/booster-crud-nodejs
17 error Linux 4.8.0-53-generic
18 error argv "/home/austincunningham/.nvm/versions/node/v6.11.4/bin/node" "/home/austincunningham/.nvm/versions/node/v6.11.4/bin/npm" "run" "openshift"
19 error node v6.11.4
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error booster-crud-nodejs@1.0.0 openshift: `nodeshift --osc.strictSSL=false`
22 error Exit status 1
23 error Failed at the booster-crud-nodejs@1.0.0 openshift script 'nodeshift --osc.strictSSL=false'.
23 error Make sure you have the latest version of node.js and npm installed.
```

**Comment by lholmquist** [comment]
We use async/await inside nodeshift, so you will need node 8+

**Comment by austincunningham** [comment]
Makes sense , verified thanks, feel free to close
